[RFC] ta: add support for OTP values
foundriesio/optee-fiovb pull request #6
Opened 2023-03-16 15:54 UTC by igoropaniuk

Add support for generic non-vendor OTP values, which can be written only once.

2023-03-16 16:44 UTC, MrCry0 requested changes

2023-03-17 12:04 UTC, igoropaniuk commented on fiovb/ta/entry.c
> +	if (check_valid_value(name_buf, REGULAR) != TEE_SUCCESS) {
Yes, you're right.

I think we can put just next if from line 116 inside this one instead of reimplementing `check_valid_value()`

2023-03-17 12:05 UTC, igoropaniuk commented on fiovb/ta/entry.c
> +	if (!check_valid_value(name_buf, OTP) ||
TEE_SUCCESS is 0 actually, so there is no proble with current if condition

2023-03-17 12:25 UTC, MrCry0 commented on fiovb/ta/entry.c
> +	if (!check_valid_value(name_buf, OTP) ||
If I understand correctly, `flags |= TEE_DATA_FLAG_ACCESS_WRITE | TEE_DATA_FLAG_OVERWRITE;` enables writing/overwriting a value whereas we should disable altering OTA/VENDOR values. The original logic is like inverted in your code - sets the WRITE/OVERWRITE flags only for OTA/VENDOR values :)

2023-03-20 16:50 UTC, closed without merging